apiVersion: 1

datasources:
- name: Alertmanager
  type: alertmanager
  access: proxy
  uid: alertmanager
  url: http://localhost:9009
  isDefault: false
  jsonData:
    httpHeaderName1: X-Scope-OrgID
  secureJsonData:
    httpHeaderValue1: hogehoge
  editable: true
