apiVersion: 1

datasources:
- name: Mimir
  type: prometheus
  access: proxy
  uid: mimir
  url: http://localhost:9009/prometheus
  isDefault: true
  jsonData:
    timeInterval: 60s
    alertmanagerUid: alertmanager
    prometheusType: Mimir
    httpHeaderName1: X-Scope-OrgID
  secureJsonData:
    httpHeaderValue1: hogehoge
  editable: true
